<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="MonoTorrent" Version="3.0.2" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.1" />
    <PackageReference Include="Telerik.Documents.CMapUtils" Version="2025.4.1216" />    
	  <PackageReference Include="Telerik.Documents.Core" Version="*" />
	  <PackageReference Include="Telerik.Documents.Fixed" Version="*" />
	  <PackageReference Include="Telerik.Documents.Fixed.FormatProviders.Image.Skia" Version="2025.4.1216" />
	  <PackageReference Include="Telerik.Documents.Fixed.FormatProviders.Ocr" Version="2025.4.1216" />
	  <PackageReference Include="Telerik.Documents.Flow" Version="*" />
	  <PackageReference Include="Telerik.Documents.Flow.FormatProviders.Pdf" Version="*" />
	  <PackageReference Include="Telerik.Documents.ImageUtils" Version="*" />
	  <PackageReference Include="Telerik.Documents.TesseractOcr" Version="2025.4.1216" />
	  <PackageReference Include="Telerik.Zip" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABC.BookCity.MariaDB\ABC.BookCity.MariaDB.csproj" />
  </ItemGroup>

</Project>
