<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ABC.DiscoveryCity.Embeddings</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pgvector" Version="0.3.0" />
  </ItemGroup>

</Project>
