services:
  bookcity-db:
    image: mariadb:10.11
    container_name: bookcity-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: bookcity
      MARIADB_USER: bookcity_user
      MARIADB_PASSWORD: bookcity_password
    ports:
      - "3306:3306"
    volumes:
      - H:/_DOCKER-DATA/mariadb:/var/lib/mysql
      - H:/Developer.BookCity/aa-data-import--temp-dir:/imports
    restart: unless-stopped

  bookcity-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: bookcity-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - H:/_DOCKER-DATA/elasticsearch:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: bookcity-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://bookcity-elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - bookcity-elastic
    restart: unless-stopped
