<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.3.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="MonoTorrent" Version="3.0.2" />
    <PackageReference Include="Telerik.Documents.CMapUtils" Version="2026.1.304" />
	  <PackageReference Include="Telerik.Documents.Core" Version="*" />
	  <PackageReference Include="Telerik.Documents.Fixed" Version="*" />
	  <PackageReference Include="Telerik.Documents.Fixed.FormatProviders.Ocr" Version="2026.1.304" />
	  <PackageReference Include="Telerik.Documents.Flow" Version="*" />
	  <PackageReference Include="Telerik.Documents.Flow.FormatProviders.Pdf" Version="*" />
	  <PackageReference Include="Telerik.Documents.ImageUtils" Version="*" />
	  <PackageReference Include="Telerik.Documents.TesseractOcr" Version="2026.1.304" />
	  <PackageReference Include="Telerik.Documents.Spreadsheet" Version="*" />
	  <PackageReference Include="Telerik.Documents.Spreadsheet.FormatProviders.OpenXml" Version="*" />
	  <PackageReference Include="Telerik.Documents.Spreadsheet.FormatProviders.Xls" Version="*" />
	  <PackageReference Include="Telerik.Zip" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABC.DiscoveryCity.DevExpressProcessing\ABC.DiscoveryCity.DevExpressProcessing.csproj" />
    <ProjectReference Include="..\ABC.DiscoveryCity.MariaDB\ABC.DiscoveryCity.MariaDB.csproj" />
    <ProjectReference Include="..\ABC.DiscoveryCity.TelerikProcessing\ABC.DiscoveryCity.TelerikProcessing.csproj" />
    <ProjectReference Include="..\ABC.DiscoveryCity.PostgreSQL\ABC.DiscoveryCity.PostgreSQL.csproj" />
    <ProjectReference Include="..\ABC.DiscoveryCity.Words.Common\ABC.DiscoveryCity.Words.Common.csproj" />
    <ProjectReference Include="..\ABC.PdfProcessing.Syncfusion\ABC.PdfProcessing.Syncfusion.csproj" />
  </ItemGroup>

</Project>
