CREATE TABLE smart_paragraphs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    book_id INT NOT NULL,
    ordinal INT NOT NULL,
    dsl_text JSONB NOT NULL,
    embedding vector(1024),
    PRIMARY KEY (book_id, id)
) PARTITION BY LIST (book_id);

CREATE INDEX ON smart_paragraphs USING ivfflat (embedding vector_cosine_ops);