namespace ABC.DiscoveryCity.DocumentIngestionProcessing.Pipeline.Steps;

/// <summary>
/// Writes an XLSX OPC bundle containing metadata, sentences, page images,
/// and the standalone HTML viewer. The bundle is a self-contained archive
/// that can be opened in Excel or unzipped for inspection.
/// </summary>
public class XlsxBundleStep : IIngestionStep
{
    public string Name => "XlsxBundle";

    public Task ExecuteAsync(IngestionContext ctx)
    {
        if (ctx.Category != FileCategory.Pdf) return Task.CompletedTask;
        if (ctx.Metadata == null) return Task.CompletedTask;
        if (ctx.DisplaySentences.Count == 0 && ctx.RenderedPages.Count == 0) return Task.CompletedTask;

        string baseName = Path.GetFileNameWithoutExtension(ctx.FilePath);
        string xlsxPath = Path.Combine(ctx.OutputDir, baseName + ".xlsx");

        // Read HTML if it was already generated by HtmlViewerStep
        string? htmlContent = null;
        string htmlPath = Path.Combine(ctx.OutputDir, baseName + ".html");
        if (File.Exists(htmlPath))
            htmlContent = File.ReadAllText(htmlPath);

        XlsxBundleWriter.Write(xlsxPath, ctx.Metadata, ctx.DisplaySentences, ctx.RenderedPages, htmlContent,
            ctx.SentenceIds.Count > 0 ? ctx.SentenceIds : null);
        Console.WriteLine($"  XLSX bundle: {baseName}.xlsx");

        return Task.CompletedTask;
    }
}
